# This is a basic workflow to help you get started with Actions

name: f5-deploy-policy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
    - 'policies/**'
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: kstachowicz/f5-waf-myactions/upload-policy@master
      with:
        waf-address: ${{ secrets.FRONT_ADDRESS }} 
        policy-filepath: ./policies/waf_policy.json
        username : ${{ secrets.WAF_USERNAME }} 
        password: ${{ secrets.WAF_PASSWORD }}
        
    - uses: kstachowicz/f5-waf-myactions/import-policy@master
      with:
        waf-address: ${{ secrets.FRONT_ADDRESS }} 
        username : ${{ secrets.WAF_USERNAME }} 
        password: ${{ secrets.WAF_PASSWORD }}
        policy-name: AppPolicy01
        
    - uses: kstachowicz/f5-waf-myactions/apply-policy@master
      with:
        waf-address: ${{ secrets.FRONT_ADDRESS }} 
        username : ${{ secrets.WAF_USERNAME }} 
        password: ${{ secrets.WAF_PASSWORD }}
        policy-name: AppPolicy01
