# This is a basic workflow to help you get started with Actions

name: f5-policy-suggestions
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

# Run workflow every 3 days (cron job format)
#on:
#  schedule:
#    - cron:  '0 0 */3 * *'

on: 
  issues:
    types: [labeled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: ${{ github.event.label.name == 'audit-approved' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
        # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
   
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2       
                
    - uses: kstachowicz/f5-waf-myactions/suggestions-pull-request@master
      id: suggestionStep
      with:
        waf-address: ${{ secrets.FRONT_ADDRESS }} 
        policy-filepath: ./policies/waf_policy.json
        username : ${{ secrets.WAF_USERNAME }} 
        password: ${{ secrets.WAF_PASSWORD }}
        policy-name: AppPolicy01
        
    
    - name: Create Pull Request
      if: ${{ steps.suggestionStep.outputs.suggestionsFound == 'true' }}
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ github.token }}
        commit-message: f5 policies suggestions
        title: New WAF policy suggestion
        body: |
          F5 has found several suggestions that you might want to consider.
          Merge code to addapt the suggestions in your policy
        branch: new-waf-policy
        labels: security  
        reviewers: kstachowicz
        
        
      
      
